-- Migração 001 — Schema inicial
-- O schema base é aplicado diretamente pelo MigrationManager via schema.py
-- Este arquivo serve apenas como registro histórico da versão 1.
-- Nenhuma ação adicional necessária.